[package]
name = "simple-rust-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
serde = {version = "1.0.217", features = ["derive"] }
warp = "0.3.7"

